### ISSUE TITLE
Upgrade modal has white text color in light mode

### ISSUE THREAD

**Issue by br4adam** [gokulkrishh/bmrk.cc#2]
**Describe the bug**
Upgrade modal has white text color in light mode

**To Reproduce**
1. Go to bmrk.cc
2. Click on Settings / Upgrade
3. Scroll down to Plan & Usage

**Expected behavior**

**Screenshots**
![IMG_0362](https://github.com/gokulkrishh/bmrk.cc/assets/104263751/1d283681-dced-4b7c-be86-e57c4d78dcab)

**Smartphone (please complete the following information):**
 - Device: iPhone 15
 - OS: iOS 17.3.1
 - Browser: Safari
 - Version: 17.3.1

**Additional context**

**Comment by gokulkrishh** [comment]
@br4adam Thanks adam for eporting, i almost missed this. It was last minute change i did that caused this issue.
