### ISSUE TITLE
Notes Related to Bookmarks

### ISSUE THREAD

**Issue by piyusharmap** [gokulkrishh/bmrk.cc#4]
**Is your feature request related to a problem? Please describe.**
When we bookmark something, there is usually a reason behind it. We often save these bookmarks in folders with appropriate names, using tags to organize them within the app. However, there are times when we bookmark something but forget to use it for an extended period. When we revisit these bookmarks, we may struggle to recall the real context or the specific content we intended to extract.

For instance, I bookmarked a TypeScript-related blog, but upon revisiting my saved bookmarks, I couldn't remember the exact information I was seeking from that particular bookmark.

To address this issue, we can introduce an additional feature: attaching a note to each bookmark. This note would serve as a reminder of the context or specific content we intended to explore. Depending on the subscription plan, we can also offer additional features related to these notes. (Only people with a subscription can edit their notes; the character limit for notes can vary depending on the subscription).

**Describe the solution you'd like**
A notes button below the timestamp which on hover can show the notes popup modal and we can easily get an idea about why we bookmarked this site.

![image](https://github.com/gokulkrishh/bmrk.cc/assets/75241694/25886490-3147-4b29-b47a-45bf3fdb247c)

**Describe alternatives you've considered**
Later we can also add a feature to remind a user about their bookmarks through email if it's marked important.

**Comment by gokulkrishh** [comment]
@piyusharmap I can understand what you are suggesting. We already have description to each bookmark, its a sort of a note or description about the site. you can edit bookmark and update with you thoughts. It always visible in front of you eyes rather than an icon or single click away to see my notes.

**Comment by piyusharmap** [comment]
Ohh that's great.
